apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - configmap.yaml
  - secret-references.yaml
  - relay.yaml
  - account.yaml
  - gateway.yaml
