apiVersion: v1
kind: ServiceAccount
metadata:
  name: relay
  namespace: aether-relay
  annotations:
    iam.gke.io/gcp-service-account: replace-with-relay-gsa@example.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: account
  namespace: aether-relay
  annotations:
    iam.gke.io/gcp-service-account: replace-with-account-gsa@example.iam.gserviceaccount.com
